### ISSUE TITLE
Embed ScalaFiddle

### ISSUE THREAD

**Issue by mkotsbak** [ThoughtWorksInc/Binding.scala#10]
Now ScalaFiddle: https://scalafiddle.io/  supports Bindings.scala, so the examples on the home page should now enable live editing of source code by embedding ScalaFiddle.

**Comment by Atry** [comment]
Good point!

I guess I have to reformat documentation soon or later.

**Comment by Atry** [comment]
I failed to port https://thoughtworksinc.github.io/Binding.scala/#9 to ScalaFiddle because `"com.thoughtworks.binding" %%% "futurebinding" % "latest.release"` is not present.

@mkotsbak Could you add `futurebinding` library?

**Comment by Atry** [comment]
https://scalafiddle.io/sf/CG4zFsf/0

```
ScalaFiddle.scala:3: error: object FutureBinding is not a member of package com.thoughtworks.binding
  import com.thoughtworks.binding.FutureBinding
         ^
ScalaFiddle.scala:26: error: not found: value FutureBinding
          val githubResult = FutureBinding(Ajax.get(s"https://api.github.com/users/${name}")) // 发起 Github API 请求，
                             ^
ScalaFiddle.scala:31: error: value responseText is not a member of Any
              val json = JSON.parse(response.responseText)                                    // 把回应解析成 JSON；
                                             ^
```

**Comment by mkotsbak** [comment]
I mentioned the problem in https://gitter.im/scalafiddle/scalafiddle

**Comment by mkotsbak** [comment]
g.scala/issues/10#issuecomment-248502493

You could try adding the library yourself and: 

"Andrea Peruffo 07:34
You can test locally using the docker or running the components
Not sure what the status of the docker is
I'll check it later"

**Comment by Atry** [comment]
I create an issue for the library https://github.com/scalafiddle/scalafiddle-core/issues/10

**Comment by oswaldo** [comment]
I have tried porting the int counter example you link from README.md and it worked (https://scalafiddle.io/sf/CIyOBmH/1) 
Maybe you could fork it, do whatever adjustment you like and replace the "other live DEMOs" link by something like "here is a live demo"

Cheers,
Oswaldo

**Comment by Atry** [comment]
@oswaldo, good catch. I have replaced these examples with ScalaFiddle versions. Thank you!
