### ISSUE TITLE
Referencing HTML DOM elements

### ISSUE THREAD

**Issue by glmars** [ThoughtWorksInc/Binding.scala#104]
`dom.currentTarget` has been deprecated and then removed.
Referencing HTML DOM element by `id` have been introduced instead.

So it is now possible to write code like this:
```scala
@dom showInput(v: Var[String]) = <div>
  <!-- any Scala code inside the div element is able to access `myInput` -->
  <input id="myInput" oninput={_: Event => v.value = myInput.value />
</div>
```

There is only one problem:
it isn't possible (very hard) to have static (global for a page) id in big and dynamic frontend application :(

Possible new feature: Binding.scala's specific attribute to form the name of the HTML DOM element variable.

```scala
@dom showInput(v: Var[String]) = <div>
  <!-- any Scala code inside the div element is able to access `myInput` -->
  <input bind:id="myInput" id="some-generated-id" oninput={_: Event => v.value = myInput.value />
  <label for="some-generated-id">First Name</label>
</div>
```

**Comment by Atry** [comment]
How about `local-id` or `local:id`?

**Comment by glmars** [comment]
I like it even more than mine. Let it be "local-id"!

I can try to create a PR, but I suppose it will be a little more difficult than before :)

**Comment by Atry** [comment]
`local-id` can be implemented as an implicit dummy attribute, like `StyleOps`.

Then, the special treatment for `id` at https://github.com/ThoughtWorksInc/Binding.scala/blob/fa4deacdead4c15a09220b5105ebe12025b5922b/dom/src/main/scala/com/thoughtworks/binding/dom.scala#L315 can be modified to `UnprefixedName("id"|"local-id")`, in order to apply to `local-id` as well.

**Comment by glmars** [comment]
Thank you.

> `local-id` can be implemented as an implicit dummy attribute, like `StyleOps`

It was my first guess. Does it look good for you? I suppose, discarding of `local-id` attribute is more clean solution.
I have prepared a PR with both variants, please, review: https://github.com/ThoughtWorksInc/Binding.scala/pull/105
