### ISSUE TITLE
scala 2.12.8 not supported

### ISSUE THREAD

**Issue by cheleb** [ThoughtWorksInc/Binding.scala#113]
Bumping scala version to 2.12.8 raises this error:
error] [...] Dashboard.scala:104:14: type mismatch;
[error]  found   : com.thoughtworks.binding.Binding[com.thoughtworks.binding.Binding.Constants[org.scalajs.dom.raw.Node]]
[error]  required: org.scalajs.dom.raw.Node
[error]             <div class="mdc-textfield" data:data-mdc-auto-init="MDCTextfield">

**Comment by Atry** [comment]
How can I reproduce it?

**Comment by cheleb** [comment]
Hi, 
  Just baked for the issu :D
  https://github.com/cheleb/scala-js-example-ap

**Comment by Atry** [comment]
I wonder if you could minimize the reproduction, like, in 10 -/+ lines of code
