### ISSUE TITLE
Boolean Attribute

### ISSUE THREAD

**Issue by sadhen** [ThoughtWorksInc/Binding.scala#118]
```
<textarea readonly></textarea>
<textarea readonly=""></textarea>
<textarea readonly="readonly"></textarea>
```

Personally, I prefer the first one.

Ref: https://www.w3.org/TR/html5/infrastructure.html#sec-boolean-attributes

**Comment by Atry** [comment]
Unfortunately currently you can only use `<textarea readonly={true}></textarea>`
