### ISSUE TITLE
Adding .map and .flatMap to trait Binding

### ISSUE THREAD

**Issue by lxohi** [ThoughtWorksInc/Binding.scala#133]
```Map``` and ```FlatMap``` are now classes inside ```com.thoughtworks.binding.Binding``` which makes them a little bit difficult to use.

And Scala compiler also fails to do the type inference because ```upstream``` & ```f``` param are inside the same pair of parentheses.

So currently I have some code like this:
```Scala
inkBar(new BMap[(Int, Int), Int](offsetWidth, _._1), new BMap[(Int, Int), Int](offsetWidth, _._2)).bind
```

Is it possible to add ```.map``` and ```.flatMap``` to ```trait Binding```?

**Comment by Atry** [comment]
Try `import scalaz.syntax.all._`

**Comment by lxohi** [comment]
Works like a charm! Thanks!

**Comment by Atry** [comment]
Feel free to create a pull request on Scaladoc for this usage.

**Comment by lxohi** [comment]
I've found there are two issues when using ```import scalaz.syntax.all._``` after having some experiences with them:

- If I have something that extends ```Binding```, for example a ```Var```. I need to use ```(var: Binding[Foo]).map``` to use these methods.
- These implicit conversions will interference with implicit conversion that from ```Binding[T]``` to ```BindingSeq[T]```

What do you think about this two issues?

**Comment by Atry** [comment]
1. Try `import com.thoughtworks.binding.Binding.BindingInstances.monadSyntax._` instead of  `import scalaz.syntax.all._`.
2. There is no implicit conversion from `Binding[T]` to `BindingSeq[T]`.

**Comment by lxohi** [comment]
Thank you so much for the reply!
I will use the first one from now 😀

And about the second one. 
Yes, these is no implicit conversion default in Binding.scala. Meanwhile I've created one in my local scope for passing the ```Binding[Node]``` to ```children: BindingSeq[Node]``` param on a component method conveniently.
But before this _implicit conversion interference_ thing, I'm actually not sure which type will be better for a [children](https://github.com/ant-design-binding/ant-design-binding/blob/19d2f41c355909f17aa5a238bddb4fc15849239a/adb-component/src/main/scala/adb/component/form/Form.scala#L10) param. Is it should be a ```BindingSeq[Node]``` or a ```Binding[BindingSeq[Node]]``` or others? Which type do you prefer?

**Comment by glmars** [comment]
> I'm actually not sure which type will be better for a children param

I suppose, there is no good answer. This is mentioned in https://github.com/ThoughtWorksInc/Binding.scala/issues/128  (please, see chapter "Containment" and the improvement 1)
