### ISSUE TITLE
Incompatible with newest version 0.6.0 of ScalaTags

### ISSUE THREAD

**Issue by pstutz** [ThoughtWorksInc/Binding.scala#2]
In build tools another dependency can easily pull in the newer version and the resulting macro errors are hard to diagnose for new users. It would make sense to update from 0.5.5 to 0.6.0 in order to make the library more approachable.

**Comment by Atry** [comment]
I guess we could wipe out the dependency to ScalaTags. The only place I use ScalaTags is here: https://github.com/ThoughtWorksInc/Binding.scala/blob/ea532c3/dom/src/main/scala/com/thoughtworks/binding/dom.scala#L140

**Comment by Atry** [comment]
Upgraded ScalaTags for now.
