### ISSUE TITLE
:= deprecated, how to use value_= ?

### ISSUE THREAD

**Issue by notyy** [ThoughtWorksInc/Binding.scala#222]
`onclick={ event: Event => githubUser_=(commandInput.value) }`

compilation failed.

**Comment by glmars** [comment]
If `githubUser` is `Var`, try this `githubUser.value = commandInput.value`. `_=` is a generic pattern in Scala for implementing a property setter.

**Comment by notyy** [comment]
yes!  I completely forgot it...

**Comment by notyy** [comment]
thank you very much @glmars
