### ISSUE TITLE
Can this library be used with IntelliJ?

### ISSUE THREAD

**Issue by joseraya** [ThoughtWorksInc/Binding.scala#24]
I am using IntelliJ as my IDE and it underlines in red all my @dom functions. I tried to open the sample project at https://github.com/ThoughtWorksInc/todo/ and I have the same problem. Is there a way to get rid of this? I have looked at the docs and could not find it.
As it seems related to the use of the macro, is there an "easy" way to define a binding without the macro?

**Comment by Atry** [comment]
This issue should be reported at https://youtrack.jetbrains.com

**Comment by Atry** [comment]
Or you could try Scala IDE for Eclipse, which handles macros.

**Comment by joseraya** [comment]
I am aware that the problem with highlighting is IntelliJ's but my question was about the possibility of using the library without the macro. Anyway, thank you very much for answering.

**Comment by kantianethics** [comment]
Scala's xml library is pretty weird. I doubt it would be possible replace the macro by defining an implicit conversion from xml.Element to Binding[ ], but perhaps @Atry has some insight on the matter.

**Comment by Atry** [comment]
Binding.scala changes type of XML literals via macros. IntelliJ IDEA seems using its own typer, which does not fully understand complex Scala syntax, even for those code that does not involve macros.

I have many Scala files that do not use macros. They are still red marked by IntelliJ IDEA.

**Comment by kantianethics** [comment]
@joseraya Thought a bit more about it, and you _can_ avoid having to use the `@dom` annotation. 

Replace xml literals with [scalatags](http://www.lihaoyi.com/scalatags/#DOMBackend)'s JSDom. 

For example: 

```scala
import scalatags.JsDom.all._

  def clicker(i: Var[Int]) = Binding[Node](
    div(
      button(onclick := {() => i := i.get + 1})("click me"),
      p("num times clicked: " + {i.bind.toString}),
      tag("test-tag")("this is a test")
    ).render
  )

  def app = Binding[Node]{
    val i = Var(0)
    div({clicker(i).bind}).render
  }

  def main(): Unit = {
    scalajs.dom.render(document.body, app)
  }

```

The only downside (upside ;) ) is that you lose xml literals

**Comment by Atry** [comment]
The entire app are recreated whenever `i` change if you don't use XML literals.

**Comment by kantianethics** [comment]
Yeah, just realized this :(

**Comment by Atry** [comment]
XHTML literals create very sophisticated ScalaTags code able to partial data-bind on each element and element.

I bet you never want to hard-code the code.

**Comment by vodkaka** [comment]
@deontologic @joseraya 
there is a trick for you, define a implicit conversion (Node -> Binding[Node])

the complier won't do the implicit conversion, it knows what happen
but intellij will be tricked, so all type is right

**Comment by ritschwumm** [comment]
@vodkaka lol, nice
