### ISSUE TITLE
Use scalatags.JSDom as default html construction library in place of xml literals

### ISSUE THREAD

**Issue by kantianethics** [ThoughtWorksInc/Binding.scala#27]
Reasoning:
- [Custom tags](https://github.com/ThoughtWorksInc/Binding.scala/issues/4) and attributes
- Fully typed
- IDE support
- No requirement on experimental macros
- The library already depends on it

**Comment by Atry** [comment]
scalatags.JSDom **is** the underlying html construction library at the moment.

**Comment by kantianethics** [comment]
Exactly. I was suggesting that it be the recommended approach in the docs. 

Definitely a personal preference, though.

**Comment by Atry** [comment]
It is. XHTML literals in a `@dom` method do create ScalaTags instead of real XML objects.
