### ISSUE TITLE
Vars size binding

### ISSUE THREAD

**Issue by romansky** [ThoughtWorksInc/Binding.scala#294]
How do I bind to the size of a Vars binding?

Using the test code in `com.thoughtworks.binding.regression.Stackoverflow58206168.scala`
I'm trying to bind to Vars so I can get the size, but this wont compile, I tried two different approaches below

```scala
{
  // See https://stackoverflow.com/questions//binding-scala-vars-bind-seems-to-not-work-correctly
  "Binding.scala: Vars.bind seems to not work correctly" in {
    val events = mutable.Buffer.empty[List[Int]]
    val test: Vars[Int] = Vars(1, 2, 3, 4)

    test.all.map {
      events += _.toList
    }.watch()

    test.value.append(1111)
    assert(events == mutable.Buffer(List(1, 2, 3, 4), List(1, 2, 3, 4, 1111)))
    assert(test.length.bind == 5)
    /* above produces error below:

`each` instructions must not appear outside monadic blocks.
  Note that the `each` instructions may be renamed for different domains.
  The renamed instruction name may be `bind`, `!`, `await`, `gen`, etc.)
    assert(test.length.bind == 5)
     */
    assert(test.all.bind.size == 5)
    /* above prodices error below

type mismatch;
 found   : com.thoughtworks.binding.Binding[test.All[Int]]
    (which expands to)  com.thoughtworks.binding.Binding[scala.collection.mutable.Buffer[_ <: Int]]
 required: com.thoughtworks.binding.Binding[scala.collection.mutable.Buffer[_$6]] where type _$6 <: Int
    assert(test.all.bind.size == 5)
     */
  }

}

```

Any ideas?

**Comment by Atry** [comment]
Could you post this question to StackOverflow, please?

Also note that you might want to read the article before post it to StackOverflow:  https://stackoverflow.com/help/how-to-ask

**Comment by romansky** [comment]
@Atry thanks for following up!
I already created a Stackoverflow issue with code reproduction here https://stackoverflow.com/questions/64103296/binding-scala-how-to-get-updating-count-from-vars?noredirect=1#comment113373456_64103296
Thanks for this great lib!

**Comment by Atry** [comment]
This is due to type inferring changes in Scala 2.13

**Comment by Atry** [comment]
This is due to naked `bind` calls. `bind` should be always inside a `Binding` block.
