### ISSUE TITLE
The Binding trait is not extendable.

### ISSUE THREAD

**Issue by fangyuanziti** [ThoughtWorksInc/Binding.scala#3]
Currently the Binding trait can not be extended easily because some private method and type. 
We need this because we want to make our existing code(which has it's own data-binding mechanism) work with Binding.scala together. We want to implement Binding trait for our own data type but find no way to do this.
Do you have a plan to change this ? Or am I missing something?

**Comment by Atry** [comment]
Have you tried to extend [SingleMountPoint](https://oss.sonatype.org/service/local/repositories/releases/archive/com/thoughtworks/binding/unidoc_2.11/9.0.0/unidoc_2.11-9.0.0-javadoc.jar/!/com/thoughtworks/binding/Binding$$SingleMountPoint.html) or [MultiMountPoint](https://oss.sonatype.org/service/local/repositories/releases/archive/com/thoughtworks/binding/unidoc_2.11/9.0.0/unidoc_2.11-9.0.0-javadoc.jar/!/com/thoughtworks/binding/Binding$$MultiMountPoint.html) instead? The two class are designed to integrate into other underlying system.

**Comment by fangyuanziti** [comment]
Thanks for you reply.
I think SingleMountPoint or MultiMountPoint can not match my need.
In my project, there are some existed codes which using [scala.tx](https://github.com/lihaoyi/scala.rx) to get a reactive variable system. All I want to do is converting a rx.Var object into binding.Var object (a wrapper for rx.Var to integrate into Binding.scala), so that I can use Binding.scala to control the web UI.
Do you have any suggestion for this?

**Comment by Atry** [comment]
Don't use Scala.rx. It leaks memory. See https://gitter.im/lihaoyi/scala.rx?at=570d17244c2125fc3f01ad88

**Comment by Atry** [comment]
Close this issue since it is not a Binding.scala bug per se.

Note that even if you have to extend `Binding`, you can still override those `private[binding]` methods in `Binding` trait.
