### ISSUE TITLE
Using BindingSeq in an implicit value class

### ISSUE THREAD

**Issue by Axiometry** [ThoughtWorksInc/Binding.scala#300]
```scala
implicit class Issue(val i: Int) extends AnyVal {
  def bindingSeq: BindingSeq[String] = Constants(42).map(_.toString)
}
```
Results in:
`Could not find proxy for   x$5: scala.this.Int in List(value x$5, value $anonfun, method bindingSeq, class Issue, module class ScalaFiddle, package class , package class ) (currentOwner= value $anonfun )`

**Comment by Atry** [comment]
See https://github.com/scala/bug/issues/11732
