### ISSUE TITLE
Use @html to create a table, what is returned is scala.xml.NodeBuffer, and what is needed is BindableSeq[org.scalajs.dom.Node],  how to convert?

### ISSUE THREAD

**Issue by vzhougm** [ThoughtWorksInc/Binding.scala#311]
![image](https://user-images.githubusercontent.com/49505436/105275873-2adca200-5bdb-11eb-95ac-5030a0fc9781.png)

**Comment by vzhougm** [comment]
`@html
  def table: BindingSeq[Node] = {
    <div>
      <button
      onclick={event: Event =>
        data.value += Contact(Var("Yang Bo"), Var("yang.bo@rea-group.com"))}>
        Add a contact
      </button>
    </div>
    <table border="1" cellPadding="5">
      <thead>
        <tr>
          <th>Name</th>
          <th>E-mail</th>
          <th>Operation</th>
        </tr>
      </thead>
      <tbody>
        {for (contact <- data) yield {
        <tr>
          <td>
            {contact.name.bind}
          </td>
          <td>
            {contact.email.bind}
          </td>
          <td>
            <button
            onclick={event: Event =>
              contact.name.value = "Modified Name"}>
              Modify the name
            </button>
          </td>
        </tr>
      }}
      </tbody>
    </table>
  }
`

**Comment by Atry** [comment]
Try another IDE

**Comment by vzhougm** [comment]
> Try another IDE

Yes, it's okay. It would be great if IDEA had the Binding.scala plugin.

**Comment by vzhougm** [comment]
use the following 😂
```scala
implicit def makeIntellijHappy(x: scala.xml.Elem): Binding[HTMLElement] = ???
implicit def makeIntellijHappy(x: scala.xml.NodeBuffer): Binding[BindingSeq[Node]] = ???
`
