### ISSUE TITLE
Text input will lost focus in a simple demo

### ISSUE THREAD

**Issue by Renkai** [ThoughtWorksInc/Binding.scala#37]
I wrote a simple demo inspired from https://thoughtworksinc.github.io/Binding.scala/#5 ,
but there is a problem that the two input boxes will lost focus after I typed any key.

Fiddle: https://scalafiddle.io/sf/Sk9YKYY/3

**Comment by Renkai** [comment]
There is a newer version with the same problem, it has something wrong with Fiddle so I paste it here.
```scala

import com.thoughtworks.binding.Binding.Var
import com.thoughtworks.binding.dom
import org.scalajs.dom.document
import org.scalajs.dom.html.Input
import org.scalajs.dom.raw.Event

import scala.scalajs.js.annotation.JSExport

@JSExport
object SampleMain {
  @dom
  def autoAdd(a: Var[Int], b: Var[Int]) = {
    val aplusb = Var[Int](a.bind + b.bind)

    def inputHandler(input: Var[Int])(event: Event) = {
      event.currentTarget.asInstanceOf[Input].value.trim match {
        case num =>
          println(s"a num.toInt = ${num.toInt}")
          input := num.toInt
      }
    }

    <div>
      a:
      <input type="text" name="fname" value={a.bind.toString} oninput={inputHandler(a)(_)}/>
      b:
      <input type="text" name="lname" value={b.bind.toString} oninput={inputHandler(b)(_)}/>
      a+b:
      {aplusb.bind.toString}
    </div>
  }

  @JSExport
  def main(): Unit = {
    val a = Var[Int](3)
    val b = Var[Int](4)
    dom.render(document.body, autoAdd(a,b))
  }
}
```

**Comment by Atry** [comment]
It's the expected behavior.
See https://github.com/ThoughtWorksInc/Binding.scala/wiki/FAQ#my-input-html-forms-misses-focusempties-when-a-var-changes and https://static.javadoc.io/com.thoughtworks.binding/unidoc_2.12/10.0.2/com/thoughtworks/binding/Binding.html#bind:A

Try to change `val aplusb = Var[Int](a.bind + b.bind)` to `val aplusb = Binding[Int](a.bind + b.bind)`
