### ISSUE TITLE
Dependency `scalajs-dom` is out dated

### ISSUE THREAD

**Issue by gcnyin** [ThoughtWorksInc/Binding.scala#383]
For current Binding.scala version `"org.lrng.binding" %%% "html" % "1.0.3+56-51cfb24a"`.

`org.scala-js » scalajs-dom_sjs1_2.13` is 0.9.8, but the newest version is 2.0.0.

**Comment by Atry** [comment]
See https://github.com/Atry/html.scala/pull/6 and https://github.com/GlasslabGames/html.scala/pull/174
