### ISSUE TITLE
Customize tags with inner html

### ISSUE THREAD

**Issue by sadhen** [ThoughtWorksInc/Binding.scala#42]
For example, https://ant.design/components/popconfirm/
``` html
// confirm, cancel are functions
<Popconfirm title="Are you sure delete this task?" onConfirm={confirm} onCancel={cancel} okText="Yes" cancelText="No">
    <a href="#">Delete</a>
</Popconfirm>
```

What I expect:
``` scala
class Popconfirm(title: String, okText: String, cancelText: String, onConfirm: Event => Unit, onCancel: Event => Unit) extend SomeTrait {
  @some_anno override def render(body: Element): Element = ???
}
```
here `render` is the function used in macros.

But this test case(https://github.com/ThoughtWorksInc/Binding.scala/blob/11.0.x/fxml/.js/src/test/scala/com/thoughtworks/binding/DateSpec.scala) shows that `<Date></Date>` is `Binding[Date]` or another type relating to `Date`. It seems `@fxml` is not suitable for customizing tags to create something like Ant Design.

In https://github.com/ThoughtWorksInc/Binding.scala/issues/4#issuecomment-273739769 ,
there are tricks to make custom tags work, but it is without any inner html (eg. `<a href="#">Delete</a>`).

**Comment by Atry** [comment]
Is the syntax difference between custom tags and custom functions important for you?

If it is not important for you, you can simply use a function like this:
``` scala
popconfirm(title="Are you sure delete this task?", onConfirm=confirm, onCancel=cancel, okText="Yes", cancelText="No") {
  <a href=" ">Delete</a >
}
```

**Comment by sadhen** [comment]
I have to admit that the syntax is important for me. I'm not sure for other people whether it is important or not? In my option, **syntax** is one reason why Binding.scala is more charming than other alternatives. 

For example, in ScalaTags and HTML literal which one you will choose to use?


**Syntax** matters a lot. In this particular example, using the `popconfirm` function is indeed more flexible and general. But custom tags syntax has the power to reduce the flexibility and make it simple and consistent.

As for me, I'm planning to develop a library based on Binding.scala and SemanticUI to provide easy-to-use custom tags like Ant Design(http://ant.design), so that programmers already familiar with Ant Design would be happy to use Binding.scala.

**Comment by sadhen** [comment]
I found a more acceptable work around:
```
<div>
<Popconfirm title="Are you sure delete this task?"
                       onConfirm={confirm}
                       onCancel={cancel}
                       okText="Yes"
                       cancelText="No"
                       inner={
      <a href="#">Delete</a>
}/>
</div>
```
Comparing with 
```
<div> {
  popconfirm(title="Are you sure delete this task?",
           onConfirm=confirm,
           onCancel=cancel,
           okText="Yes",
           cancelText="No") {
    <a href=" ">Delete</a >
  }
} </div>
```
, which one do you prefer ?

**Comment by maxkorolev** [comment]
+1, that would be awesome

**Comment by csoren** [comment]
This would be great for consuming web components, such as the ones defined by Polymer.

**Comment by skaz1970** [comment]
> Is the syntax difference between custom tags and custom functions important for you?
> 
> If it is not important for you, you can simply create a `popconfirm` function and use it like this:
> 
> ```scala
> popconfirm(title="Are you sure delete this task?",
>            onConfirm=confirm,
>            onCancel=cancel,
>            okText="Yes",
>            cancelText="No") {
>   <a href=" ">Delete</a >
> }
> ```

Please, show body (with return type) of popconfirm

**Comment by Atry** [comment]
``` scala
import com.thoughtworks.binding.dom
import org.scalajs.dom.raw._
import org.scalajs.dom.document

@dom def popconfirm(
  title: String,
  okText: String, cancelText: String,
  onConfirm: Event => Unit, onCancel: Event => Unit
)(
  // For FXML, use `Binding[Node]` instead of `Node`
  message: Node 
) = {
  <section>
    <h3>{ title }</h3>
    <div>
    { message }
    </div>
    <button type="button" onclick={onConfirm}>{
      okText
    }</button>
    <button type="button" onclick={onCancel}>{
      cancelText
    }</button>
  </section>
}

@dom
def render = popconfirm(title="Are you sure delete this task?",
          onConfirm={ _ =>
            println("confirm")
          },
          onCancel={ _ =>
            println("cancel")
          },
          okText="Yes",
          cancelText="No") {
  <a href=" ">Delete</a >
}.bind // .bind should be avoided for FXML

dom.render(document.body, render)
```

**Comment by skaz1970** [comment]
Thanks a lot!

**Comment by skaz1970** [comment]
But if I'd like to get instead of `message: Node` different types, `Binding[Node]`, `BindingSeq[Node]`, `BindingSeq[Option[Node]]`? Can you propose anything? Is there any common type?

**Comment by skaz1970** [comment]
Thanks, my thought were around `BindingSeq[Node]`, but converting makes code less readable.

**Comment by sadhen** [comment]
I'm trying to implement the inner html feature in https://github.com/sadhen/Binding-SemanticUI
