### ISSUE TITLE
Two piece of code get different result but should got the same(maybe).

### ISSUE THREAD

**Issue by Renkai** [ThoughtWorksInc/Binding.scala#46]
https://scalafiddle.io/sf/cTYNGtw/1 get result `3,4`, which is expected result.

https://scalafiddle.io/sf/cTYNGtw/2 get `3,4,5,6,7,3,4`, which should be wrong.

The only difference is if `.bind` is used in the for loop.

**Comment by Atry** [comment]
It's not a bug.

It's the expected behavior.

See Scaladoc.
