### ISSUE TITLE
Nested elements

### ISSUE THREAD

**Issue by turbolent** [ThoughtWorksInc/Binding.scala#48]
It seems like accessing nested elements after constructing them using XML literals doesn't work:

```scala
val div = <div><div>Nested</div></div>
div.childNodes.length == 0
```

Rendering `div` afterwards works like expected though.

Example: https://scalafiddle.io/sf/6ZzWXB2/2
This should print 
```
nested div: [object HTMLDivElement]
div children: 1
```

**Comment by Atry** [comment]
Thank you for reporting. The behavior indeed confuses people.

This usage will be disabled in the future, when we replace `@dom` to `@html`: https://groups.google.com/d/msg/scala-js/L1mkQqVLizQ/UEHzjqgqCgAJ

**Comment by Atry** [comment]
Maybe that's only my own feeling. I thought it would be better if an annotation does not change the return type.

**Comment by glmars** [comment]
Hmm... Something was changed in Binding.scala `10.0.3` -> `11.0.0`. I have migrated @turbolent example to Binding.scala `11.0.0` and it works as expected now!
https://scalafiddle.io/sf/qUPotrB/3 should print (I changed the example slightly):
```
div innerHTML:
Nested

div children: 1
```

**Comment by Atry** [comment]
Yes.
This behavior is changed in 8bc7845167d7c661ec126fbed2f05632b978b459

**Comment by glmars** [comment]
So, this issue was fixed in Binding.scala 11.0.0 and you can close it, aren't you?

**Comment by Atry** [comment]
Yes. I am closing it.

`@html` is an idea that did not include in Binding.scala v11
