### ISSUE TITLE
How to run some init code after @dom component loaded to dom

### ISSUE THREAD

**Issue by jilen** [ThoughtWorksInc/Binding.scala#53]
[SO Link](https://stackoverflow.com/questions/44917823/how-to-execute-some-init-after-element-loaded-to-dom-with-biding-scala)
Given a component
```scala
@dom 
def chart = {
  <canvas id="chartCanvas"><canvas>
}
```
How can I init the canvas with some chart library like chartjs when it is loaded to dom ?

**Comment by Atry** [comment]
Not a bug
