### ISSUE TITLE
How can i use nativescript with Binding.scala?

### ISSUE THREAD

**Issue by baram204** [ThoughtWorksInc/Binding.scala#57]
I want to make mobile app quick and easy.
so, [nativescript](https://www.nativescript.org/nativescript-example-application?utm_medium=referral&utm_source=documentation&utm_campaign=getting-started) is looks good.

![nativescript](https://user-images.githubusercontent.com/11155414/28702607-0c3f384a-7399-11e7-8b6c-75d01a7adf4d.gif)

There are similar project [sri](https://github.com/chandu0101/sri). but I don't want to use facade and learn complex ReactNative and convent new convert way.

so how can I use nativescript with Binding.scala?

I'm a newbee. So I just asking you some advice.

**Comment by Atry** [comment]
I don't know nativescript. Maybe you could ask about it on [StackOverflow](http://stackoverflow.com/).
