### ISSUE TITLE
Converting from BindingSeq to ObservableList

### ISSUE THREAD

**Issue by oleg-py** [ThoughtWorksInc/Binding.scala#65]
I was investigating if `Binding.scala`'s FXML support will work for one of my personal projects, and quickly ran into issue trying to create a simple table:

```scala
import javafx.application.Application
import javafx.stage._
import javafx.scene._
import javafx.scene.control._

import com.thoughtworks.binding.Binding.Constants
import com.thoughtworks.binding._

final class FxmlTest extends Application {
  @fxml override def start(primaryStage: Stage): Unit = {
    type StringTable = TableView[String]
    val scene: Binding[Scene] =
      <Scene>
        <StringTable> {Constants("Hello", "Flatmap")}</StringTable>
      </Scene>
    fxml.show(primaryStage, scene)
  }
}

object FxmlTest {
  def main(args: Array[String]): Unit = {
    Application.launch(classOf[FxmlTest], args: _*)
  }
}
```

Results in this error:
```
[error] [E1] src/mco/ui/FxmlTest.scala
[error]      type mismatch;
[error]       found   : com.thoughtworks.binding.Binding.Constants[String]
[error]       required: javafx.collections.ObservableList[String]
[error]      L16:        <StringTable> {Constants("Hello", "Flatmap")}</StringTable>
[error]      L16:         ^
```

It does not work if I use `Seq` instead, too.

I found a [related issue on SO](https://stackoverflow.com/questions/44195066/binding-scala-fxml-how-to-populate-an-observablelist-property) but could not find a way to trigger implicit conversion, if there is one.

**Comment by Atry** [comment]
I'll fix it when I have time

**Comment by Atry** [comment]
According to JavaFX specification:

https://docs.oracle.com/javase/8/javafx/api/javafx/fxml/doc-files/introduction_to_fxml.html#read_only_list_property_elements

> A read-only list property is a Bean property whose getter returns an instance of `java.util.List` and has no corresponding setter method. The contents of a read-only list element are automatically added to the list as they are processed.

`items` is a list property of `StringTable`, however, it is not a `read-only` as there is a setter [setItems](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TableView.html#setItems-javafx.collections.ObservableList-). As a result, Binding.scala does append content of the `Constants` to the `items` property, instead, it tries to assign the XML interpolation code via `setItems`.

That is to say, the current behavior of Binding.scala is extractly correct according to the specification.

**Comment by Atry** [comment]
This behavior is very inconvenient, so I decide to break the specification, allowing appending content of the data-binding expressions to any list properties, no matter it is read-only or not.

We can do better than the original Java specification. That's why you choose Binding.scala.
