### ISSUE TITLE
Each instructions message appears randomly 

### ISSUE THREAD

**Issue by baank** [ThoughtWorksInc/Binding.scala#66]
The following code produces an "`each` instructions must be inside a SDE block" error message even though it doesn't doesn't match any of the conditions for when it should normally appear e.g. not within @dom section.

```
case class CheckboxElement(name: Var[String],
            label: Var[String],
            checked: Var[Boolean] = Var(false)) extends Component {

	@dom def render() = {
		<label class="checkbox-inline checkbox-right">
		<input name={ name.bind } type="checkbox" class="styled"/>
		{ label.bind }
		</label>
	}
}
```

**Comment by Atry** [comment]
Looks like you forgot `addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)`
