### ISSUE TITLE
Creating a BindingSeq 

### ISSUE THREAD

**Issue by gmkumar2005** [ThoughtWorksInc/Binding.scala#69]
I am trying to create a function layout which will return multiple nodes. 
```
 @dom
  def renderLayout(): Binding[BindingSeq[Node]] = {
    val bSNavBar = new BSNavBar(MockData.menuData)
    <div class="container">
      {bSNavBar.renderNavBar.bind}
    </div>

      <div class="container">
        {bSNavBar.renderNavBar.bind}
      </div>

  }
```

If fails to compile with type mismatch : found NodeBuffer
Also the code mentioned in documentation does  not compile.  type mismatch : found NodeBuffer. 
`@dom def node: Binding[BindingSeq[org.scalajs.dom.raw.HTMLBRElement]] = <br/><br/>`

How to return multiple nodes ?

**Comment by gmkumar2005** [comment]
I am using 
"com.thoughtworks.binding" %%% "dom" % "11.0.0-M3"
addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)

Plugins
addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.6")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.21")
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.3")

**Comment by Atry** [comment]
Does it work on https://scalafiddle.io/ ?

**Comment by gmkumar2005** [comment]
The example in the documentation works in https://scalafiddle.io/
My use case is to be able to compose a larger page with smaller components eg : page is composed of header + buttons + menus. 
I have added queries in the following link
https://scalafiddle.io/sf/z7ZsryH/5

**Comment by Atry** [comment]
Good
