### ISSUE TITLE
Are there a way to manipulate DOM?

### ISSUE THREAD

**Issue by vincentdchan** [ThoughtWorksInc/Binding.scala#80]
I use Binding.Scala to implement a `tab`, I want to use external library such as *Chart.js* to generate a chart in a tab, I don't find a good way to do it.

In *React.js*, maybe I will get the **ref** of a HTMLElement and manipulate it, but I don't know how to do it in `Binding.scala`.

I know Binding.scala doesn't have lifecycle, but it should be a way to work around.

**Comment by Atry** [comment]
Binding.scala do have lifecycles.

Check
[StackOverflow](https://stackoverflow.com/questions/44917823/how-to-execute-some-init-after-element-loaded-to-dom-with-binding-scala/45101054) and [Scaladoc](https://javadoc.io/page/com.thoughtworks.binding/binding_2.12/latest/com/thoughtworks/binding/Binding$$SingleMountPoint.html)

**Comment by vincentdchan** [comment]
@Atry Thx!
